version: "3.8"

services:
  postgres-db:
    image: postgres:16
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: pms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - 5432:5432

  pms:
    build:
      context: .
      dockerfile: Dockerfile
    image: pms-app:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pms
    networks:
      - db-network
    ports:
      - 8080:8080
    depends_on:
      postgres-db:
        condition: service_healthy

networks:
  db-network:

volumes:
  postgresdata:
